version: '3'
services:
  nginx:
    image: nginx:1.12.2
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - /data:/data
  php:
    image: mp-php:1.0
    working_dir: /data
    #build:
    #  context: ../services/php
    #  dockerfile: Dockerfile
    volumes:
      - ./etc/php:/etc/php
      - /data:/data
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123123"
    volumes:
      #- ./mysql/log:/var/mysql/log
      - ./etc/mysql:/etc/mysql
    ports:
      - "3306:3306"
  memory:
    image: redis:3.2.1
    ports:
      - "6379:6379"
  analysis:
    image: mp-python:1.0
    command: /bin/sh -c "while true; do echo 1; sleep 3600; done" & 
    volumes:
      - /data/analysis:/data/analysis
      - /data/nebula/gflow:/data/nebula/gflow
