version: '3'
services:
  nginx:
    image: nginx:1.12.2
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - /data:/data
  php:
    image: php-yaf:1.0
    working_dir: /data
    #build:
    #  context: ../services/php
    #  dockerfile: Dockerfile
    volumes:
      - ./etc/php:/etc/php
      - /data:/data
  mysql:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123123"
    volumes:
      #- ./mysql/log:/var/mysql/log
      - ./etc/mysql:/etc/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:3.2.1
    ports:
      - "6379:6379"
